name: fitbitter
description: A Flutter package to make your life easier when dealing with Fitbit APIs.
version: 2.0.1
homepage: https://github.com/gcappon/fitbitter

environment:
  sdk: '>=2.18.0 <3.0.0'
  #flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_auth: ^0.4.1 #used to implement oauth 2.0
  dio: ^4.0.6 #better web browser
  logger: ^1.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
