name: fitbitter
description: A Flutter package to make your life easier when dealing with Fitbit APIs.
version: 2.0.4
homepage: https://github.com/gcappon/fitbitter

environment:
  sdk: '>=3.0.0 <4.0.0'
  #flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_auth: ^0.6.0 #used to implement oauth 2.0
  dio: ^5.7.0 #better web browser
  logger: ^2.5.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
